language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetcdf-dev
notifications:
  flowdock: 7a05b97b59127301baa1b87fe93b3c41
